[workspace]
members = [
    "crates/drivers",
    "crates/utils/logging",
    "crates/firmware",
    "crates/controllers/foc",
    "crates/utils/pid",
    "crates/utils/units",
    "crates/controllers/controller_shared",
    "crates/utils/crc_engine",
    "crates/transport",
    "crates/cli",
    "crates/server",
    "crates/command_handler",
    "crates/communication",
    "crates/user_config",
    "crates/bootloader",
    "crates/hardware"
, "crates/led_manager", "crates/settings"]
resolver = "3"

[profile.release]
lto = "fat"
debug = 2

[profile.release.package.firmware]
codegen-units = 1
opt-level = 3
