[package]
name = "units"
version = "0.1.0"
edition = "2024"

[dependencies]
uom = { version = "0.37.0", default-features = false, features = ["f32", "si", "autoconvert"] }
portable-atomic = {version = "1.11.1", features = ["float"]}