[package]
name = "controller-shared"
version = "0.1.0"
edition = "2024"

[features]
defmt = ["dep:defmt", "foc/defmt"]

[dependencies]
defmt = {version = "1.0.1", optional = true}
foc = {path = "../foc"}