[package]
name = "foc"
version = "0.1.0"
edition = "2024"

[features]
defmt = ["hardware-abstraction/defmt", "shared/defmt"]
log = ["hardware-abstraction/log", "shared/log"]

[dependencies]
hardware-abstraction = { path = "../hardware_abstraction" }
shared = { path = "../shared" }
